version: '3'

services: 
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  spring-petclinic-1:
    image: spring-petclinic-docker
    depends_on:
      - mysql
    ports:
      - 8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
  spring-petclinic-2:
    image: spring-petclinic-docker
    depends_on:
      - mysql
    ports:
      - 8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306
  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8083:80
    depends_on:
      - spring-petclinic-1
      - spring-petclinic-2
    links:
      - spring-petclinic-1:spring-petclinic-1
      - spring-petclinic-2:spring-petclinic-2